#!/usr/bin/env bash
# Behavioral regressions for ask-user authority instructions generated by ap-brief.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

BRIEF="$ROOT/bin/ap-brief.sh"
TMP_ROOT=$(ap_test_tmproot ap-ask-user-authority)

test_primary_and_copilot_instruction_generation() {
  local home flight charter
  home="$TMP_ROOT/home"
  mkdir -p "$home/data"

  AP_HOME="$home" AP_ROOT_OVERRIDE="$ROOT" \
    "$BRIEF" authority-worker sample >/dev/null 2>&1
  flight="$home/data/authority-worker/brief.md"
  assert_grep 'ask-user findings are never yours to answer' "$flight" \
    "generated implementation brief lets the worker own an ask-user decision"
  assert_grep "Autopilot applies the authority contract in its \`AGENTS.md\`" "$flight" \
    "generated implementation brief bypasses the primary authority owner"
  assert_grep "silently bypass autopilot's authority check and any required pilot escalation" "$flight" \
    "generated implementation brief permits silent ask-user auto-resolution"
  assert_no_grep 'the pilot, not you, owns the ask-user decisions' "$flight" \
    "generated implementation brief retained conflicting pilot-only wording"

  AP_HOME="$home" AP_ROOT_OVERRIDE="$ROOT" AP_COPILOT_CHARTER='Handle sample work.' \
    "$BRIEF" authority-copilot --copilot --no-projects >/dev/null 2>&1
  charter="$home/data/authority-copilot/brief.md"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'The local `AGENTS.md` is your job description' "$charter" \
    "generated copilot charter does not load the tracked authority boundary"
  assert_no_grep 'continuous frame-by-frame monitoring' "$charter" \
    "generated copilot charter duplicated the detailed authority procedure"
  pass "primary workers and copilots receive the authority rule through generated instructions"
}

test_primary_and_copilot_instruction_generation
